// examples/angular/src/main.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import '@endeavoury/finance-design';
@Component({
  selector: 'app-root',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<ds-container size="narrow"
    ><ds-stack gap="6"
      ><ds-page-header
        eyebrow="Angular example"
        heading="Native custom elements"
        description="Angular property and event bindings target the same Web Components."
      ></ds-page-header
      ><ds-metric
        label="Current value"
        [value]="name()"
        tone="accent"
        detail="Updated through ds-input"
      ></ds-metric
      ><ds-input
        label="Display name"
        [value]="name()"
        (ds-input)="name.set($any($event).detail.value)"
      ></ds-input
      ><ds-checkbox [checked]="enabled()" (ds-change)="enabled.set($any($event).detail.checked)"
        >Enabled</ds-checkbox
      ><ds-button (click)="name.set('Saved consumer')">Save</ds-button
      ><ds-alert tone="success" heading="Shared implementation"
        >No Angular component owns visual behavior.</ds-alert
      ></ds-stack
    ></ds-container
  >`,
})
class App {
  readonly name = signal('Angular consumer');
  readonly enabled = signal(true);
}
bootstrapApplication(App).catch(console.error);

// examples/react/src/main.tsx
import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import '@endeavoury/finance-design/styles.css';
import {
  Alert,
  Button,
  Checkbox,
  Container,
  Input,
  Metric,
  PageHeader,
  Stack,
} from '@endeavoury/finance-design-react';
function App() {
  const [name, setName] = useState('React consumer');
  return (
    <Container size="narrow">
      <Stack gap="6">
        <PageHeader
          eyebrow="React example"
          heading="Thin typed adapters"
          description="React renders the same ds-* Web Components."
        />
        <Metric
          label="Current value"
          value={name}
          tone="accent"
          detail="Updated by a typed custom event"
        />
        <Input
          label="Display name"
          value={name}
          onDsInput={(event) => setName(event.detail.value)}
        />
        <Checkbox checked onDsChange={(event) => console.info('checked', event.detail.checked)}>
          Enabled
        </Checkbox>
        <Button onClick={() => setName('Saved consumer')}>Save</Button>
        <Alert tone="success" heading="Shared implementation">
          No React component owns visual behavior.
        </Alert>
      </Stack>
    </Container>
  );
}
createRoot(document.getElementById('root')!).render(<App />);
